- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
- fail:
    msg: "The system may not be provisioned according to the CMDB status."
  when: "to-be-staged" != "to-be-staged"
